jobs:
  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - run: node --version
      - run: npm --version
      - run: yarn --version
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Run Unit Tests
          command: yarn --cwd frontend test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: 'reports/junit/js-test-results.xml'
      - store_artifacts:
          path: reports
      - store_test_results:
          path: reports/junit
orbs:
  node: circleci/node@2.0.3
version: 2.1

workflows:
  default:
    jobs:
      - test
