jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/project/frontend
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: node --version
      - run: yarn --cwd frontend install
      - run: yarn --cwd frontend add jest-junit
      - run:
          name: Run Jest tests
          command: yarn --cwd frontend test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: 'reports/junit/js-test-results.xml'
      - store_artifacts:
          path: ./test-results/junit
      - store_test_results:
          path: ./test-results
orbs:
  node: circleci/node@2.0.3
version: 2.1
workflows:
  test_my_app:
    jobs:
      - install-node-example
