jobs:
  simple-jest-tests:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
        install-yarn: true
        node-version: latest
      - run: node --version
      - run: yarn --cwd frontend install

orbs:
  node: circleci/node@2.0.3
version: 2.1
workflows:
  test_my_app:
    jobs:
      - simple-jest-tests
