jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/frontend
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: node --version
      - run: yarn install
      - run: yarn test
orbs:
  node: circleci/node@2.0.3
version: 2.1
workflows:
  test_my_app:
    jobs:
      - install-node-example
