jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/project
    steps:
      - checkout:
          path: frontend
      - node/install:
          install-yarn: true
          node-version: latest
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn --cwd frontend install
      - run: yarn --cwd frontend add jest-junit
      - run:
          name: Run Jest tests
          command: yarn --cwd frontend test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: 'reports/junit/js-test-results.xml'
      - store_artifacts:
          path: reports
      - store_test_results:
          path: reports/junit
orbs:
  node: circleci/node@2.0.3
version: 2.1
workflows:
  test_my_app:
    jobs:
      - install-node-example
